SONG_FILE_FORMAT = 'mp3'

SECONDS_PER_MINUTE = 60
MILLIS_PER_SECOND = 1000

TIME_DELTA_TILL_NEXT_DOWNLOADS_CHECK = 10

DEFAULT_DOWNLOADS_DIR_NAME = 'Downloads'

DOWNLOAD_WAIT_TIMEOUT_PER_FILE = 10
